version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/ideaexchange
    overwrite: true
permissions:
  - object: /var/www/html/ideaexchange/codedeploy
    pattern: "*.sh"
    owner: root
    group: root
    mode: 777
    type:
      - file
hooks:
  BeforeInstall:
    - location: codedeploy/before_install.sh
      timeout: 180
  AfterInstall:
    - location: codedeploy/after_install.sh
      timeout: 1000
  ApplicationStart:
    - location: codedeploy/app_start.sh
      timeout: 180
  ApplicationStop:
    - location: codedeploy/app_stop.sh
      timeout: 180
      


